before_install: gem install bundler --pre
language: ruby
rvm:
 - 2.1.0
before_install:
  - gem install bundler #force to install bundler 1.5.1, (1.5.0 fails json)
  - gem --version
env:
  - RAILS=3.2.16
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - COVERALLS=1 bundle exec rspec spec/

